CREATE SEQUENCE seq_citizen_id
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_permit_type_id
  START WITH 100
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_department_id
  START WITH 10
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_application_id
  START WITH 10000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_review_step_id
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_license_id
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_document_id
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_application_number
  START WITH 20250001
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;